<?php require 'templates/header.phtml' ?>
    <div class="alert alert-warning mx-auto w-50 mt-3 d-flex justify-content-center" role="alert">
        <div class="d-flex flex-column">
            <h1 class="display-6">
               ¿Esta seguro de querer cerrar sesion?
            </h1>
            <div class="mx-auto w-30">
                <a type="button" class="btn btn-success" href="logout">Si</a></button>
                <a type="button" class="btn btn-danger" href="inicio">No</a></button>
            </div>
        </div>
    </div>
<?php require 'templates/footer.phtml' ?>