<?php include './templates/header.phtml' ?>

<div class=" w-25 mx-auto">
    <form action="modificar" method="POST">
        <div class="mt-2 form-group">
            <label for="" class="form-label">Vinilo:</label>
            <input class="form-control" type="text" name="vinilo" aria-label="readonly input example" >
        </div>

        <div class="mt-2 form-group">
        <label for="" class="form-label">Año Lanzamiento:</label>
            <input class="form-control" type="text" name="anio"  aria-label="readonly input example" >
        </div>
        <div class="mt-2 form-group">
        <label for="" class="form-label">Precio:</label>
            <input class="form-control" placeholder="precio" type="text" name="precio"  aria-label="readonly input example" >
        </div>
        <div class="mt-2 form-group">
            <label for="inputPassword5" class="form-label">Id vinilo:</label>
            <input class="form-control" placeholder="precio" type="text" name="id-vinilo"  aria-label="readonly input example" >
        </div>
        <button type="submit"  class=" mt-2 btn btn-info">Modificar</button>
    </form>

</div>

<?php if ($error) : ?>
    <div class='alert alert-danger' role='alert'>
        <?= $error ?>
    </div>
<?php endif ?>


<?php include './templates/footer.phtml' ?>