<?php include './templates/header.phtml'; var_dump($idArt)?>

<div class=" w-25 mx-auto">
    <form action="modificar-artista/<?=$idArt?>" method="POST">
        <h1 class="display-6">Modificar descripción</h1>
        <div class="mt-2 form-group">
            <label for="" class="form-label">Descripcion:</label>
            <textarea class="form-control" name="descp" id="floatingTextarea2" style="height: 100px"></textarea>
        </div>
        <button type="submit"  class=" mt-2 btn btn-info">Modificar</button>
    </form>

</div>


<?php include './templates/footer.phtml' ?>