<?php include './templates/header.phtml'
; var_dump($idVinilo) ?>

<div class=" w-25 mx-auto">
    <form action="modificar-vinilo/<?=$idVinilo?>" method="POST">
        <h1 class="display-6">Modificar Precio</h1>
        <div class="mt-2 form-group">
        <label for="" class="form-label">Precio:</label>
            <input class="form-control" placeholder="5000" type="number" name="precio"  aria-label="readonly input example" >
        </div>
        <button type="submit"  class=" mt-2 btn btn-info">Modificar</button>
    </form>

</div>


<?php include './templates/footer.phtml' ?>