<?php require 'templates/header.phtml' ?>

<div class="mt-5 w-25 mx-auto p-2">
    <h1 class="display-6 fs-3">Login:</h1>
</div>
<div class=" w-25 mx-auto">
    <form action="auth" method="POST">
        <div class="form-group">
            <label for="email">Email</label>
            <input type="text" required class="form-control" name="email" aria-describedby="emailHelp">
        </div>
        <div class="form-group">
            <label for="password">Contraseña</label>
            <input type="password" required class="form-control" name="pass">
        </div>

        <?php if ($error) : ?>
            <div class='alert alert-danger' role='alert'>
                <?= $error ?>
            </div>
        <?php endif ?>

        <button type="submit" class="btn btn-primary mt-3">Entrar</button>
    </form>
</div>