<?php include './templates/header.phtml';
//require_once './app/controllers/auth.controller.php'; 
?>


<div class=" w-25 mx-auto">
    <h1 class="display-6 text-center">Vinilos disponibles</h1>
</div>
<!-- Lista todos los vinilos, junto con año de lanzamiento y precio -->
<div class="p-3">
    <table class="table ">
        <thead class="table-dark">
            <tr>
                <th>Vinilo </th>
                <th>Año Lanzamiento </th>
                <th>Precio </th>
                <?php if(AuthHelper::isLogued()): ?>
                <th>Acciones</th>
                <?php endif ?>    
            </tr>
        </thead>

        <?php foreach ($items as $item) : ?>
            <tbody>
                <td><a href="detalle-vinilo/<?= $item->id_vinilo ?>"> <?= $item->vinilo; ?></td>
                <td> <?= $item->anio_lanzamiento; ?> </td>
                <td> $<?= $item->precio ?>ARS </td>
                <?php if(AuthHelper::isLogued()): ?>
                <td><a href="eliminar-vinilo/<?= $item->id_vinilo ?>" type="button" class="btn btn-outline-success">Borrar</a>
                    <a href="editar-vinilo/<?= $item->id_vinilo ?>" type="button" class="btn btn-outline-success">Modificar</a>
                </td>
                <?php endif ?>   
            <?php endforeach ?>

            </tbody>

    </table>
    <?php if(AuthHelper::isLogued()): ?>
        <div class="d-flex flex-row">
            <div class="p-2 ">
                <ul class="navbar-nav d-flex flex-row">
                    <li class="nav-item"><a href="form-insertar-vinilo" type="button" class="btn btn-outline-success">Insertar</a></li>
                </ul>
            </div>
        </div>
    <?php endif ?>
</div>